### ISSUE TITLE
Change severity for code smells

### ISSUE THREAD

**Issue by losserl** [Pablissimo/SonarTsPlugin#101]
Hi,

We want to change the severity from major to minor for one of the rules. Therefore we have add a new line <name rule>.severity=MINOR.
We compile the project and put the jar in Sonar-plugins-directory and restart the Sonar-server.

Then we check the source code with Sonar and the changed rule had been violated, but with severity major (instead of minor). When we click on the violated rule to see more information about it, then we see that the severity is minor.

Can you help us how we can change the severity to minor, so we can see this in the first overview.

Best regards, 
Lida

**Comment by Pablissimo** [comment]
So typically to override severity of a rule you do it through the admin interface (i.e. you don't need to recompile anything). Hit up the Quality Profiles, find the rule you want to amend and click into it - hit Change then alter the severity.

So far as I know, the plugin's default severities only get applied the first time SonarQube sees the rule - if a plugin upgrade changes the severity of a rule you've already got activated I'm not sure that it'll update in your profile. I'm kind of surprised it shows as minor when you click through, really. You could try creating a new rules profile and applying it to your project then re-analysing?

**Comment by losserl** [comment]
OK. Thanks!
I have changed the severity in the Dashboard. Run Sonar again and now the code smells have severity minor .
