### ISSUE TITLE
TsLint Err: /bin/node: /bin/node: cannot execute binary file

### ISSUE THREAD

**Issue by NickKitchen** [Pablissimo/SonarTsPlugin#107]
Hi,

I'm trying to use the plugin for a jenkins project, but every ts file is followed by the error "TsLint Err: /bin/node: /bin/node: cannot execute binary file" when trying to process it.

The job completes as successful, but no rules are processed. Any hint as to what I might be doing wrong?

Thanks

Nick

**Comment by Pablissimo** [comment]
Can you post the bits of your sonar-project.properties file that start `sonar.ts` please? Also:

- If you can configure your Jenkins build to do it, get the -X parameter sent to the scanner to get debugging output and attach the output here
- List what version of the scanner, SonarQube itself, `tslint` and the plugin you're using

Should help us get started!

**Comment by NickKitchen** [comment]
Sorry, discovered the sonarqube version was only 5.1.

I've setup a new test environment with 6.2 and the latest plugin, tslint and scanner and the error no longer occurs. I have different issues due to tslint not liking my project, but that is a different issue ;-)

Sorry to waste your time...

**Comment by Pablissimo** [comment]
Never a problem, the version requirements are not made mega clear but glad you're up and running!
