### ISSUE TITLE
Configure for travis-ci analysis of plugin on sonarqube.com

### ISSUE THREAD

**Issue by Pablissimo** [Pablissimo/SonarTsPlugin#110]
In preparation for trying to get the plugin listed within SonarQube itself, get automated analysis configured and running as part of the CI build.

**Comment by nixel2007** [comment]
I can show you our jenkins config for sonar-l10n-ru plugin with analysis on SQ.com (via mvn sonar:sonar with parameters)  and some real life examples with Travis runs if you need any help. Just @ ping me.

**Comment by Pablissimo** [comment]
So I managed to cobble together a script before noticing your kind offer, so I've at least got analysis taking place on my own SonarQube instance (https://sonar.pablissimo.com/dashboard?id=com.pablissimo.sonar%3Asonar-typescript-plugin for its sins, seems there are some issues to resolve!).

Would be curious how you set things up in Travis to avoid performing an SQ step if you're receiving a pull request - my .travis.yml feels heroically hacky at the minute...

**Comment by nixel2007** [comment]
@Pablissimo 

jenkins maven build job with this goals:
```
clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.sonarsource.scanner.maven:sonar-maven-plugin:LATEST:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SonarOAuthToken}
```

Triggers configured for `master` branch polling.

Travis config: [yaml](https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/blob/master/.travis.yml) and [sh with branch filtering (develop and PRs)](https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/blob/master/travis.sh)

**Comment by Pablissimo** [comment]
<3 thanks, will take a look!
