### ISSUE TITLE
Code Coverage not visible in measures only in individual files

### ISSUE THREAD

**Issue by nuphoff** [Pablissimo/SonarTsPlugin#113]
Code coverage is not visible in Home or Measures tab, but when i navigate to the individual files it does show which lines were covered.

See the screenshots below

Configuration:
Sonarqube 5.6.4
Typescript plugin 1.0.0-RC1

![sonarqube-home](https://cloud.githubusercontent.com/assets/4758951/22971928/c4631218-f377-11e6-81c7-e3e611a931a7.png)
![sonarqube-measures](https://cloud.githubusercontent.com/assets/4758951/22971931/c466f81a-f377-11e6-8a06-7a8d1a45d2f6.png)
![sonarqube-coverage](https://cloud.githubusercontent.com/assets/4758951/22971930/c463b5f6-f377-11e6-95c5-c1c79c859c04.png)
![sonarqube-individualfile](https://cloud.githubusercontent.com/assets/4758951/22971965/e9194bd6-f377-11e6-9dfb-a0f1d7b8e501.png)

**Comment by Pablissimo** [comment]
That's irksome - any chance you can attach your example project and sonar-project.properties file please? I've got a 5.6.2 instance that I regression test on locally, and the 'basic-setup' sample project seems to yield coverage info just fine:

![image](https://cloud.githubusercontent.com/assets/1470336/22995822/4d56ae62-f3c4-11e6-9829-981d6f1e2c5c.png)

Would be interested to hear if you get the same when analysing the basic-setup sample project in the repo?

**Comment by nuphoff** [comment]
Thank you for the quick response.

It's probably an issue with sonarqube itself because i have tried it on a bigger project more than 12 lines of code and then the coverage does show up, maybe there is a treshold of somesort?
