### ISSUE TITLE
sonar.ts.tslint.path config always needed, even when re-using tslint output

### ISSUE THREAD

**Issue by oliverbrandt** [Pablissimo/SonarTsPlugin#114]
When re-using a tslint output generated by the build process, sonar.ts.tslint.path still needs to be configured and pointing to an existing file. 
If that is not the case, the plugin provides the message "[WARNING] Path to tslint not defined or not found. Skipping tslint analysis." and stops the analysis.

**Comment by Pablissimo** [comment]
Ha, damn that's daft - thanks for the PR, will take a look.
