### ISSUE TITLE
Directory path handling with symlinks

### ISSUE THREAD

**Issue by oliverbrandt** [Pablissimo/SonarTsPlugin#118]
The current working dir is something like /export/.., where /export is a link to mounted file system /export0.

The tslint output contains the canonical path (/export0/..) where as the FileSystem implementation by SonarQube provides the "simple" path (/export/...).

This leads to a warning during analysis "TsLint reported issues against a file that isn't in the analysis set - will be ignored: /export0/...".

**Comment by Pablissimo** [comment]
Why did you revert the fix on your branch but leave the PR, out of interest?

**Comment by oliverbrandt** [comment]
As this is my first attempt on juggling branches, I messed things up. I reverted the change on another branch as it ended up there also. But as far as I can tell, the commit is still on the canonical-path branch.

**Comment by Pablissimo** [comment]
Cool, no worries - as mentioned on the PR I'll need some time to test on a couple of environments (assuming this is a Linux-specific issue?), want to make sure nothing's regressed anywhere.

**Comment by oliverbrandt** [comment]
Yes, we ran into the issue on Linux.
