### ISSUE TITLE
Inconsistent whitespace in the repos

### ISSUE THREAD

**Issue by alexkrauss** [Pablissimo/SonarTsPlugin#13]
We have a number of small contributions in the pipeline (fix for linux, update of rule definitions, maybe more...), but producing proper pull requests is a bit cumbersome, since whitespace use is highly inconsistent in the repository. Many editors normalize this automatically, but this produces diffs that are very hard to read.

Would you accept a PR that normalizes all whitespace (use only space, no tab), removes all trailing whitespace and adds an .editorconfig (most editors respect this automatically)? I'm not religious about the exact conventions used, but it is good to have a convention...

**Comment by Pablissimo** [comment]
Yep, fire on

**Comment by alexkrauss** [comment]
Closing, as of #14.
