### ISSUE TITLE
Extension folder not correct in Readme?

### ISSUE THREAD

**Issue by samuelpath** [Pablissimo/SonarTsPlugin#132]
In the Readme, we have:

> Copy .jar file (from target/ after build, or downloaded from Releases page) to **SonarQube extensions folder**
> Restart SonarQube server
> Browse to SonarQube web interface, login as Admin, hit up Settings
> Find the TypeScript tab, paste in the TsLint path

When I followed these instructions, the TypeScript tab didn't show up in my web interface.
However, when I put the .jar file into the /extensions/plugins/ folder, it worked.

I'm using SonarQube-5.6.3.

Should this be corrected, or am I the only one having had this issue?

**Comment by Pablissimo** [comment]
No that's a bug in the README sorry, should be corrected - ideally it wouldn't be there at all and would just link to the official SonarQube documentation on installing plugins. Good spot - will happily accept a PR or will fix myself tonight.

Hopefully the plugin will be in the Update Centre before long so the manual installation steps can be less prominent!
