### ISSUE TITLE
Does the tslint.json override the SonarQube TsLint quality profile?

### ISSUE THREAD

**Issue by ZoeThivet** [Pablissimo/SonarTsPlugin#150]
Simple question, I guess the answer is yes but I want to be 100% sure.

Rule disabled in quality profile + enabled in tslint.json = enabled in analysis?
Rule enabled in quality profile + disabled in tslint.json = disabled in analysis?

Thank you :)

**Comment by nixel2007** [comment]
No, if rule is disabled ad QP it won't be enabled or counted.

**Comment by ZoeThivet** [comment]
Alright, thank you.
