### ISSUE TITLE
Config project dependent

### ISSUE THREAD

**Issue by 304NotModified** [Pablissimo/SonarTsPlugin#153]
I think this is a feature request,

I would be great if we could set the typescript analyser settings project dependent, e.g. a .json config file for the following settings:

![image](https://user-images.githubusercontent.com/5808377/27732837-77e742f2-5d93-11e7-9285-7f58ad95dc75.png)

**Comment by Pablissimo** [comment]
Not sure I understand what you mean I'm afraid, can you elaborate?

**Comment by 304NotModified** [comment]
The settings, eg ignore pattern, is now for all projects on one machine. 

It would be great to set the ignore pattern for one project (on multiple machines by checking in the config it git for example)

**Comment by Pablissimo** [comment]
Wait - within that Visual Studio extension, or were you just using it as an example?

**Comment by 304NotModified** [comment]
Ah oops, wrong github repo. Sorry!

**Comment by Pablissimo** [comment]
Haha, no worries - I was trying to think of a way to break it to you gently...
