### ISSUE TITLE
SonarQube fails to start with sonar.core.serverBaseUrl error

### ISSUE THREAD

**Issue by admiralAwkbar** [Pablissimo/SonarTsPlugin#164]
I have tried to install the release 1.1.0 plugin to my sonarqube 6.3.1 instance.
When i restart the instance with the plugin in place, it fails to start the server with error:
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: sonar.core.serverBaseURL=https://my-sonar-server.com and sonar.core.serverBaseURL=https://my-sonar-server.com

Where could i fix this in the plugin source?

Current installed plugins:
checkstyle-sonar-plugin-3.6.1.jar       
sonar-csharp-plugin-5.9.0.1001.jar    
sonar-issueresolver-plugin-1.0.2.jar        
sonar-ldap-plugin-2.1.0.507.jar     
sonar-timeline-plugin-1.5.jar
qualinsight-sonarqube-badges-3.0.1.jar  
sonar-css-plugin-3.1.jar              
sonar-java-plugin-4.9.0.9858.jar            
sonar-php-plugin-2.10.0.2087.jar    
sonar-typescript-plugin-1.1.0.jar.hold
README.txt                              
sonar-findbugs-plugin-3.4.4.jar       
sonar-javascript-plugin-3.0.0.4962.jar      
sonar-pmd-plugin-2.6.jar            
sonar-web-plugin-2.5.0.476.jar
sonar-auth-github-plugin-1.3.jar        
sonar-gherkin-plugin-1.3.jar          
sonar-jdepend-plugin-1.1.1.jar              
sonar-puppet-plugin-1.4.jar         
sonar-widget-lab-plugin-1.8.1.jar
sonar-build-breaker-plugin-2.1.jar      
sonar-github-plugin-1.4.1.822.jar     
sonar-jproperties-plugin-2.5.jar            
sonar-python-plugin-1.7.0.1195.jar  
sonar-xml-plugin-1.4.2.885.jar
sonar-cfamily-plugin-4.8.0.7665.jar     
sonar-googleanalytics-plugin-1.1.jar  
sonar-json-plugin-2.2.jar                   
sonar-rci-plugin-1.0.1.jar
sonar-clover-plugin-3.1.jar             
sonar-groovy-plugin-1.5.jar           
sonar-karma-test-report-plugin-1.0.0.4.jar  
sonar-scm-git-plugin-1.2.jar

**Comment by Pablissimo** [comment]
Can you give us a fuller error log? The only thing I've seen this happen with has been on an upgraded-from-an-older-version SonarQube instance where the server-level configuration has an authentication-related key defined twice but the proper error log would help.
