### ISSUE TITLE
SonarTsPlugin in Oficial Docker Sonar Image

### ISSUE THREAD

**Issue by drjoju** [Pablissimo/SonarTsPlugin#167]
Hi,

I'm trying to install the plugin on the official docker image. I installed the .jar package in the plugins folder and it looks good in general settings -> TypeScript.

The problem comes installing nodejs to install tslint. I do:
apt-get update
apt-get install nodejs

I see nodejs version 4.8.2 installed but I don't find npm.

> nodejs --version
v4.8.2
> npm
sh: 4: npm: not found

I know it's a docker problem but i asks if anyone knows how to install it so it will appear in the documentation for this plugin.

Thanks and best regards

**Comment by nixel2007** [comment]
The official way to install new versions of node is described here https://nodejs.org/en/download/package-manager/

Try it, it should be shipped with npm

**Comment by drjoju** [comment]
Thanks nixel2007, you put me in the way

in docker you need to install in this way.

> curl -sL https://deb.nodesource.com/setup_6.x | bash -
> sudo apt-get install -y nodejs

This works.

> nodejs --version
v6.11.1
> npm --version
3.10.10
