### ISSUE TITLE
readme needs updating

### ISSUE THREAD

**Issue by westwick** [Pablissimo/SonarTsPlugin#187]
there are still references to `sonar.ts.tslint.lcovReportPath` although it appears this has been updated to `sonar.typescript.lcov.reportPaths`

additionally I cant find any documentation about other sonar.ts properties not being referenced as sonar.typescript instead and am having trouble loading my projects tslint.json so I wonder what else has changed along these lines.

the readme should be updated to reflect these changes and I'm happy to open a PR but don't know the full scope of the changes.

**Comment by nixel2007** [comment]
Please make sure you use plugin from this repo, and not a official one.

**Comment by westwick** [comment]
yes it is this package, from my dockerfile: `RUN wget 'https://github.com/Pablissimo/SonarTsPlugin/releases/download/v1.1.0/sonar-typescript-plugin-1.1.0.jar' -P extensions/plugins`

**Comment by westwick** [comment]
sorry you are right somehow the other extension was enabled :( my bad

**Comment by nixel2007** [comment]
This plugin has the same pluginKey. So if you install this version then go to update center... The official plugin will be installed because it has bigger version number. :)
