### ISSUE TITLE
TS code scanning does not return error but tslint returns a list of errors

### ISSUE THREAD

**Issue by cccedi** [Pablissimo/SonarTsPlugin#188]
Hi,
i am having a strange issue -  for TS sources, the sonarQube runs but does not return errors. 
All parameters are passed. Any idea what could be wrong. Thanks.

My sonar-project.properties has the following - 
sonar.projectKey=CCW:20feb11
sonar.projectName=CCW20feb11
sonar.projectVersion=0.1
sonar.scm.disabled=true
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.ts.tslint.path=node_modules/tslint/bin/tslint
sonar.exclusions=**/node_modules/**
sonar.ts.tslint.configpath=tslint.json
sonar.report.export.path=sonar-report.json

The logs of sonar-scanner -X are attached - 
[CCW-logs.txt](https://github.com/Pablissimo/SonarTsPlugin/files/1740200/CCW-logs.txt)

The tslint.json & tsconfig.json are also attached in the following zip file - 
[jsonfiles.zip](https://github.com/Pablissimo/SonarTsPlugin/files/1740206/jsonfiles.zip)

Thanks in advance.
Ed

**Comment by nixel2007** [comment]
> 15:38:51.046 DEBUG:   * SonarTS 1.5.0.2122 (typescript)

You use the official ts plugin from SonarSource, not this one.
