### ISSUE TITLE
Custom rules are all put in the 'unknown rule breach' bucket

### ISSUE THREAD

**Issue by Pablissimo** [Pablissimo/SonarTsPlugin#24]
Since the plugin doesn't know about custom rules (other than passing the parameter to TsLint) it can't translate rule breaches into sensibly named items for the SonarQube analysis and instead a custom rule breach is treated the same as we'd treat any other unknown rule breach - into the 'generic unknown error' bucket.

Would probably have to have this configured via some global configuration file, but should investigate if we can somehow do this dynamically at sonar-runner run-time.

**Comment by drywolf** [comment]
@Pablissimo I created PR #31 that implements this functionality :wink:

**Comment by Pablissimo** [comment]
Resolved by @drywolf in release 0.7
