### ISSUE TITLE
custom rules are loaded from the rules-dir but no output is generated

### ISSUE THREAD

**Issue by drywolf** [Pablissimo/SonarTsPlugin#26]
Hi,

This is the issue following up on my comments about custom tslint rules not being reported during analysis in #18.

What I found out is that the rules are being loaded from the rules-dir, but they don't seem to be evaluated by the sonar-runner for some reason.
I added some logging to the plugin and had a look at what the sonar-runner output looked like and there was no occurrance of any of my custom rules.

I even manually added the rule to the plugin and built it from source, but there was still no output for the custom rule that I added.

Is there anything special that I should be careful about when using custom rules to make them work with the plugin ?

EDIT:
tsc-version: Version 1.9.0-dev.20160323
tslint-version: 3.7.1

Thanks

**Comment by Pablissimo** [comment]
Are they listed in your ````tslint.json```` to be used? Do they appear in tslint output if run manually?

**Comment by drywolf** [comment]
@Pablissimo I figured out that the output from the custom rules is not shown if I run the tslint command from a command line manually. Usually I run tslint for my projects through npm scripts and if I do that the custom rules are working just fine. But if I use the exact same command on the regular command line the output by the custom-rules is gone.

But if I rename a custom rule to an incorrect name in the tslint.json and try to run the command line I get and error still. So the custom rules are recognized, by they are simply not handled and/or their output is not shown when tslint is run in a global CLI context instead of npm.

I'll continue debugging this ... have you ever heard before of such an issue with tslint ?

**Comment by Pablissimo** [comment]
No, and I've got custom rules running on several of the projects on the demo site (I had to implement support for --custom-rule-dir exactly because ````tslint```` refused to even parse ````tslint.json```` files if they contained rules it didn't recognise.

If you run sonar-runner with the -X switch it should give you the trace output from tslint - you will see screeds of JSON output but hopefully you can dig into that to see if tslint's reporting any breaches of your custom rule?

Will try and repro locally, but do you have a sample project you can fire on?

**Comment by drywolf** [comment]
Ok i dug a bit deeper ... my rules actually only work if I run tslint from the node_modules\.bin\ working directory of my project. If I try to run the exact same command somewhere else, all the custom rules go away.

To me it really seems like some odd dependency problem is going on between the tslint in my node_modules folder and the tslint that is globally installed on my computer.
:confused:

**Comment by drywolf** [comment]
I updated the typescript dependency in my module from `Version 1.9.0-dev.20160315` to `Version 1.9.0-dev.20160408` (typescript@next) and the problem seems to be gone.

Not sure what the exact root cause of the problem was, but in the end it seems to have been just another funky npm dependency problem :laughing:
