### ISSUE TITLE
Can't launch runner from distant client due to invalid tslint path

### ISSUE THREAD

**Issue by cyrilgandon** [Pablissimo/SonarTsPlugin#30]
The tslint path is configured on the server, but when I try to launch a runner on a distant machine, it seems that the runner try to find tslint with the path of the server on my local machine.

Maybe one option would be to ship the plugin with tslint wrapped in, and give the option to the user to specify a custom tslint in the global configuration and by projects.

**Comment by Pablissimo** [comment]
I'm wary of bundling a version of ````tslint```` with the plugin as we've just taken steps to try to decouple the versions of plugin from analysis tool, but if it were configurable at project-level there'd be nothing to stop you running it wherever you wished.

Alternative would be to allow detection of a project-local version of ````tslint```` in the runner if nothing else is configured (i.e. look for a node_modules\tslint folder relative to sonar-project.properties) as a default fallback?

**Comment by cyrilgandon** [comment]
I love the idea to search for a tslint in local node_modules, that made a lot of sense.

**Comment by Pablissimo** [comment]
This has now been implemented in [v0.8-Pre](https://github.com/Pablissimo/SonarTsPlugin/releases/tag/v0.8), along with a change that lets you specify the path to tslint at a global or project level so that individual projects can override it as required.
