### ISSUE TITLE
[for contributors] Generate code coverage reports for the SonarTsPlugin

### ISSUE THREAD

**Issue by drywolf** [Pablissimo/SonarTsPlugin#33]
Hi,

is there a way to check the code coverage for the SonarTsPlugin on a local dev machine already ?
I just tried out [JaCoCo](http://eclemma.org/jacoco/) and it worked pretty well.
If there is interest and there is no way to get coverage reports yet, I could create a PR with the necessary additions to pom.xml.

Regards

**Comment by Pablissimo** [comment]
Sure, try ````mvn cobertura:cobertura```` as a target - it's what the Travis CI build runs for [Coveralls](https://coveralls.io/r/Pablissimo/SonarTsPlugin?branch=master)

**Comment by drywolf** [comment]
Thanks for the hint, cobertura does the trick.
