### ISSUE TITLE
What are the basic configuration properties?

### ISSUE THREAD

**Issue by mayooran99** [Pablissimo/SonarTsPlugin#36]
How do I specify the source path and other basic configuration properties in my Jenkins? Please advice.

**Comment by Pablissimo** [comment]
Source path for what? Not sure I understand!

**Comment by mayooran99** [comment]
Yes source path and ignoring tests for sonar.

**Comment by Pablissimo** [comment]
Well the plugin doesn't provide anything extra beyond the core SonarQube properties that control those two things: http://docs.sonarqube.org/display/SONAR/Analysis+Parameters

Having never used Jenkins I'm unsure what effect it'd have, if any, on how you configure this stuff - when you invoke the SonarQube analysis runner it'll so far as I know look for a sonar-project.properties file in the working directory and then operate from there.

**Comment by Pablissimo** [comment]
e.g. http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Jenkins would be probably the set of steps to get Jenkins triggering a SonarQube analysis, then a minimal sonar-project.properties would probably look something like the below, adjusted for folder names relative to the sonar-project.properties file path.

This is what I use for the analysis of the Microsoft Visual Studio Code project on the [demo site](https://sonar.pablissimo.com) - you can skip the last three items if you're not excluding any files, using code coverage or using custom TsLint rules.

````
sonar.projectKey=vscode
sonar.projectName=Microsoft Visual Studio Code
sonar.projectVersion=1.0
sonar.souceEncoding=UTF-8

sonar.ts.excludetypedefinitionfiles=true
sonar.ts.tslintconfigpath=tslint.json

sonar.sources=src/
sonar.exclusions=**/test/**/*,**/*.d.ts

sonar.ts.lcov.reportpath=coverage/lcov.dat
sonar.ts.tslintrulesdir=build/lib/tslint
````

**Comment by Pablissimo** [comment]
Unclear what more I can do with this, closing.
