### ISSUE TITLE
Integration with TFS/VSTS build

### ISSUE THREAD

**Issue by rfennell** [Pablissimo/SonarTsPlugin#41]
No really an issue but I thought it might be useful to link to how I got this plugin working with TFS/VSTS and Sonarqube. I have [documented it in this post](http://bit.ly/29jH6ju)

Not sure if there is an easier way at present?

**Comment by Pablissimo** [comment]
Suspect that's the most straightforward approach just now (it's not something I've locally tested for a long while). Will link from the readme if that's OK?

Also - if you've got ideas on improvements for TFS/VSTS integration then please raise 'em as issues!

**Comment by Pablissimo** [comment]
Readme updated with link to blog
