### ISSUE TITLE
SonarQube 6.0

### ISSUE THREAD

**Issue by JKatGSD** [Pablissimo/SonarTsPlugin#53]
Hi,

we updated our SonarQube-Instance to Version 6.0.
Since this update your **great** Plugin is not working anymore.

Area you planing to get this work again?

Here the Exception:
`10:34:15 Exception in thread "main" java.lang.NoSuchMethodError: org.sonar.api.resources.File.fromIOFile(Ljava/io/File;Lorg/sonar/api/resources/Project;)Lorg/sonar/api/resources/File;
10:34:15 	at com.pablissimo.sonar.TsCoverageSensor.fileFromIoFile(TsCoverageSensor.java:110)
10:34:15 	at com.pablissimo.sonar.TsCoverageSensor.saveMeasureFromLCOVFile(TsCoverageSensor.java:93)
10:34:15 	at com.pablissimo.sonar.TsCoverageSensor.analyse(TsCoverageSensor.java:59)
10:34:15 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
10:34:15 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
10:34:15 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
10:34:15 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184)
10:34:15 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
10:34:15 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
10:34:15 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
10:34:15 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
10:34:15 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
10:34:15 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
10:34:15 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
10:34:15 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
10:34:15 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
10:34:15 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
10:34:15 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
10:34:15 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
10:34:15 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
10:34:15 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
10:34:15 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:34:15 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:34:15 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:34:15 	at java.lang.reflect.Method.invoke(Method.java:498)
10:34:15 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
10:34:15 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
10:34:15 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
10:34:15 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
10:34:15 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
10:34:15 	at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
10:34:15 	at org.sonarsource.scanner.cli.Main.main(Main.java:60)`

**Comment by Pablissimo** [comment]
Yep, known issue - I am planning to fix it but getting married this weekend so won't get to it until end of the month I'm afraid!



Sent from a mobile device - apologies for any errors as a result


-------- Original message --------

**Comment by JKatGSD** [comment]
It doesn't care if you take a **bit** longer ;)

May your future be blessed with love and happiness! 👍

**Comment by chiefmc** [comment]
@Pablissimo are you still a happy honeymooner? :)

**Comment by Pablissimo** [comment]
Ha! Sadly back to reality now. Will update issue #49 too but I have a very preliminary version of the plugin that should support SonarQube 5.6+ including SonarQube 6.0:

https://github.com/Pablissimo/SonarTsPlugin/releases/tag/v0.93

I can't stress enough how preliminary SonarQube 6.0 support is, and that I've almost certainly regressed something in reworking things to support the updated API but locally on a few test cases on both Windows and Linux it appears to broadly work as it did before. Your mileage may vary etc...

**Comment by charpour** [comment]
That's great, thanks so much Pablissimo!!

Looking forward to a more mature version that supports SonarQube, whenever it's available :-)

**Comment by Pablissimo** [comment]
Closed with v0.94, now released.
