### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/base/Objects

### ISSUE THREAD

**Issue by IGZmarcosrivera** [Pablissimo/SonarTsPlugin#58]
Hi!

When I try to make a coverage test y receive the following error:

_WARN: ----------------------------------------------------------------
WARN: Sonargraph Integration: Skipping projectXXXXXXXXXX [XXXXXXXXXXX], since no Sonargraph rules are activated in current SonarQube quality profile [TsLint].
WARN: ----------------------------------------------------------------
INFO: Sensor Lines Sensor
INFO: Sensor Lines Sensor (done) | time=28ms
INFO: Sensor Sonar-Sonargraph-Plugin [3.5]
INFO: ----------------------------------------------------------------
INFO: Sonargraph: Skipping project [XXXX] XXXXXXXX [XXXXXXX], since no Sonargraph rules are activated in current SonarQube quality profile.
INFO: ----------------------------------------------------------------
INFO: Sensor Sonar-Sonargraph-Plugin [3.5] (done) | time=2ms
INFO: Sensor SCM Sensor
INFO: Sensor SCM Sensor (done) | time=32ms
INFO: Sensor XmlFileSensor
INFO: Sensor XmlFileSensor (done) | time=1ms
INFO: Sensor Linting sensor for TypeScript files
INFO: Sensor Linting sensor for TypeScript files (done) | time=4257ms
INFO: Sensor Combined LCOV and LOC sensor
INFO: Analysing /XXXXX/XXXXXXXXXX/lcov.info
WARN: Problem during processing LCOV report: can't save DA data for line 0 (Line with number 0 doesn't belong to file app/app.ts).
**Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Objects**
	at com.pablissimo.sonar.LCOVParserImpl$FileData.addBranch(LCOVParserImpl.java:200)
	at com.pablissimo.sonar.LCOVParserImpl.parse(LCOVParserImpl.java:126)
	at com.pablissimo.sonar.LCOVParserImpl.<init>(LCOVParserImpl.java:60)
	at com.pablissimo.sonar.LCOVParserImpl.create(LCOVParserImpl.java:73)
	at com.pablissimo.sonar.TsCoverageSensorImpl.getParser(TsCoverageSensorImpl.java:106)
	at com.pablissimo.sonar.TsCoverageSensorImpl.saveMeasureFromLCOVFile(TsCoverageSensorImpl.java:81)
	at com.pablissimo.sonar.TsCoverageSensorImpl.execute(TsCoverageSensorImpl.java:141)
	at com.pablissimo.sonar.CombinedCoverageSensor.execute(CombinedCoverageSensor.java:34)
	at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)_

I fix this adding the library guava-19.0.jar to your plugin in path: _META-INF/lib/_ and now the plugin works (I don't know if I did it right but as I say, It works for me)

**Comment by IGZmarcosrivera** [comment]
Excuse me, I forgot the jar and sonarqube version:

Sonarqube: 5.6.2
typescript-plugin: 0.93-SNAPSHOT

**Comment by Pablissimo** [comment]
So v0.93 was intended to be the SonarQube 6.0 supporting branch, but it looks as though there're a couple of regressions around that guava library (check out the pull requests for one that fixes things for SQ 6.0). What's odd is that I can't recreate the issue...

What version of the sonar-runner are you using, and what OS? You should in theory be safe with v0.8 or v0.9 (Windows only, there're a couple of Linux-specific bugs in there) unless you need SQ 6.0 support, but I'll try to repro with the above extra information!

**Comment by IGZmarcosrivera** [comment]
Ok, thank you.
I am running sonar-runner in OSX and Linux. The version is:

_WARN: sonar-runner script is deprecated. Please use sonar-scanner instead.
INFO: Scanner configuration file: /usr/local/Cellar/sonar-runner/2.7/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 2.7
INFO: Java 1.8.0_101 Oracle Corporation (64-bit)
INFO: Mac OS X 10.11.6 x86_64_

I will check with developers the upgrade to Sonar 6.0

Thank you

**Comment by Pablissimo** [comment]
Would try the 0.8 version of the pluin before upgrading, suspect you might get the same problem with 6.0



Sent from a mobile device - apologies for any errors as a result


-------- Original message --------

**Comment by IGZmarcosrivera** [comment]
With 0.8 version works fine!
But it's curious why with version 0.9 we had the path problem and with this version no...

**Comment by IGZmarcosrivera** [comment]
Ok, it works but doesn't send the coverage results to sonarqube. 

As I said, I'll talk with developers to upgrade sonarqube to version 6.

Thank you for all!!

**Comment by Pablissimo** [comment]
So v0.8 didn't handle spaces in paths on Windows at all well, and so broke in a number of situations. v0.9 was intended to fix that, but had the unexpected side-effect of breaking most (though oddly not all) Linux usages of the plugin.

The fix for that was rolled into v0.93, which then in turn seems to have broken some combinations of SQ and the runner with this Guava thing (but confusingly not all, since I've got it working on a 5.6.1 box and a 6.0 box).

Sounds like there's a gap in my test environments where I'm not picking this stuff up!
