### ISSUE TITLE
Exclude parameter

### ISSUE THREAD

**Issue by dangler** [Pablissimo/SonarTsPlugin#61]
I want to be able to exclude directories from being linted. I.E. node_modules

**Comment by philipooo** [comment]
Have you tried to place your sources into a sub-folder and assign this folder to `sonar.sources=<yoursubfolder>` ?

**Comment by dangler** [comment]
I was able to get it to work with this option. Didn't know about that since it's not included in the docs for the plugin.

sonar.exclusions=**/node_modules/**

Thank you for the response.

**Comment by philipooo** [comment]
It is not mentioned in the docs because its an option of SonarQube itself and not of the plugin. Here you can find some more informations if you have not seen yet http://docs.sonarqube.org/display/SONAR/Narrowing+the+Focus

Cheers
