### ISSUE TITLE
Execution failure

### ISSUE THREAD

**Issue by aymenhouissa** [Pablissimo/SonarTsPlugin#66]
Hello,

I'm facing a problem when running this plugin. It fails at the execution phase.
Is there any idea please ?
I've attached the log file.

Regards
`
13:09:10 13:09:10.515 ERROR - TsLint Err: Error: Cannot find module '/home/jenkins/workspace/Build Front end with Sonar/"/home/jenkins/workspace/Build Front end with Sonar/node_modules/tslint/bin/tslint"'
13:09:10 13:09:10.515 ERROR - TsLint Err:     at Function.Module._resolveFilename (module.js:469:15)
13:09:10 13:09:10.516 ERROR - TsLint Err:     at Function.Module._load (module.js:417:25)
13:09:10 13:09:10.516 ERROR - TsLint Err:     at Module.runMain (module.js:604:10)
13:09:10 13:09:10.516 ERROR - TsLint Err:     at run (bootstrap_node.js:394:7)
13:09:10 13:09:10.516 ERROR - TsLint Err:     at startup (bootstrap_node.js:149:9)
13:09:10 13:09:10.516 ERROR - TsLint Err:     at bootstrap_node.js:509:3`

[trace.txt](https://github.com/Pablissimo/SonarTsPlugin/files/569028/trace.txt)

**Comment by Pablissimo** [comment]
Looks like the defect that I'd hoped I'd fixed in v0.94 - what version are you running?

**Comment by aymenhouissa** [comment]
I've used the v0.9. should I upgrade ?

**Comment by Pablissimo** [comment]
Yeah, either to the latest (which has changes for Sonarqube 6 too) or this if you want something nearer to what you have but with the fix in place: https://github.com/Pablissimo/SonarTsPlugin/files/440852/sonar-typescript-plugin-0.92-SNAPSHOT.zip

**Comment by Pablissimo** [comment]
Just a note, you need to restart SonarQube after updating the plug in version - it'll keep running the old version till you do.

**Comment by aymenhouissa** [comment]
Thanks!
