### ISSUE TITLE
Newer rules of tslint are not showing up on webview.

### ISSUE THREAD

**Issue by oomprakash** [Pablissimo/SonarTsPlugin#67]
Hi,

**Below configurations of sonar:**
sonarqube-5.6
sonar-typescript-plugin-0.9-SNAPSHOT.jar
Scanner version 2.6.1, running from command prompt

**sonar-project.properties**
sonar.ts.tslintpath=../../../Users/user_name/AppData/Roaming/npm/node_modules/tslint/bin/
sonar.ts.tslintconfigpath=tslint.json

Sonar server scanning code as per tslint.json's rule set which is newer than previous one 2.4.x as I was using previously. Newer version of tslint has more rule set but they are not showing up in web view so when user sees the error or code smells as per newer rules he/she gets confused that without rule set how is it showing errors.
	
Is there any way to showing up rules on web view from tslint.json?

**Comment by Pablissimo** [comment]
So - we need to update the plugin to accommodate the new rule names, but anything that's unrecognised *should* currently be going into a generic bucket shown below. So if that's not happening then that's a bug, but I'll update the configuration based on this issue this weekend with luck, it's typically not a difficult process...

![image](https://cloud.githubusercontent.com/assets/1470336/20217088/2298f72e-a816-11e6-842a-3c7b97ac8c18.png)
