### ISSUE TITLE
Incompatibility with tslint 4.0.0

### ISSUE THREAD

**Issue by Pablissimo** [Pablissimo/SonarTsPlugin#70]
Via @charpour:

I've tried 0.95 against tslint@4.0.0, but the run failed with the following error:

```
01:55:45 INFO: Sensor Linting sensor for TypeScript files
01:55:47 INFO: ------------------------------------------------------------------------
01:55:47 INFO: EXECUTION FAILURE
01:55:47 INFO: ------------------------------------------------------------------------
01:55:47 INFO: Total time: 1:32.425s
01:55:47 INFO: Final Memory: 59M/383M
01:55:47 INFO: ------------------------------------------------------------------------
01:55:47 ERROR: Error during SonarQube Scanner execution
01:55:47 ERROR: 54 is not a valid line for pointer. File [moduleKey=<some_ts_file>, basedir=<some_directory>] has 24 line(s)
```

**Comment by danielb-paymark** [comment]
I can confirm this works with gradle sonar plugin.

**Comment by kefliyuksel** [comment]
Same Problem here.

**Comment by Pablissimo** [comment]
So - I think what's happening is a side-effect of TsLint 4.0.0's fix to their broken JSON output when multiple files are provided. The plugin used to have several expectations around the format of the incoming data that are no longer valid with 4.0.0. Needs a rewrite of the tslint -> sensor path which doesn't look *too* painful, just needs a bit of finesse to keep backwards-compatible with < 4.0.0.

Fix underway, ish, though.

**Comment by Pablissimo** [comment]
Do you want to give the below spike a try? Appears to work with tslint 3.5 and tslint 4.0.0+ but my test cases are limited. No proper release yet, unit tests don't even build yet let alone run - needs a bit of fixing up from some signature changes. Don't forget to restart SonarQube after updating (removing the old plugin version), and is provided pre-release and used at your own risk etc etc.

[sonar-typescript-plugin-0.96-SNAPSHOT.zip](https://github.com/Pablissimo/SonarTsPlugin/files/633810/sonar-typescript-plugin-0.96-SNAPSHOT.zip)

**Comment by nixel2007** [comment]
@Pablissimo I'll try on my local instance for my ts-projects

**Comment by Pablissimo** [comment]
Hmm, managed to break it locally which is a bit exciting - I would suggest holding off.

**Comment by Pablissimo** [comment]
Ok, 4.0.0 itself seems to have an issue but 4.0.2 appears happy enough

**Comment by nixel2007** [comment]
![image](https://cloud.githubusercontent.com/assets/1132840/20925939/e7482c9e-bbca-11e6-97b3-29088dba81b2.png)
looks like everything is working on 4.0.2

**Comment by nixel2007** [comment]
tested on projects with 1k and 17k LOC

**Comment by Pablissimo** [comment]
I've not yet updated it with the new rules that 4.0.2 brings (it's deprecated some, and introduced some others) so I'll add those in before making this a 'public' release but glad it seems to do the trick, thanks for testing!

**Comment by nixel2007** [comment]
@Pablissimo thanks for your work!
