### ISSUE TITLE
Pass --project and --type-check parameters to tslint

### ISSUE THREAD

**Issue by NikitaEgorov** [Pablissimo/SonarTsPlugin#75]
How can i pass  --project and --type-check to tslint?

**Comment by Pablissimo** [comment]
Can't just now - I can probably add a configuration parameter to allow extra arguments to be sent. Or specifically add configuration options for those two params...

I should have a little time over Christmas while hiding from the in-laws to have a look.

**Comment by Pablissimo** [comment]
So this is an interesting one - there's an outstanding defect on tslint that essentially means that if you supply both the --project parameter and a list of files, the list of files is ignored and tslint only pays attention to the files listed in the project json file.

This is tricky for us for two reasons:
- We currently batch files to send to tslint so they don't end up creating a command line that's too long on systems with small limits - but if tslint's ignoring the set of files it's sent and always using the project file then we're doing loads of work in tslint then ignoring the results
- People using the --project option would need to maintain both their sonar-project.properties file *and* their tsconfig.json file to make sure they're pointing to the same sets of files unless the above is fixed

Any feeling on what a sensible approach would be? Best thinking I have so far is, if you've specified a path to tsconfig.json:
- Turn off batching, no longer send a list of files to tslint but trust that tsconfig.json has been setup right
- If tslint reports lint violations for files that aren't in our analysis set as defined by sonar-project.properties, ignore those violations

**Comment by Pablissimo** [comment]
Also - what would you want to achieve by passing --type-check to tslint that your existing CI build isn't capturing? There's no output from tslint that I can supply to SonarQube if a type-check fails, so far as I know, so it'll just abort the SQ analysis entirely if there are any typing errors. Might be fine, just wondering what the use-case is?

**Comment by Pablissimo** [comment]
Got it. Have started along the lines of my original proposal since it seems to fit well enough - travelling the next week but should have time in airports and the like to bash through I reckon.

**Comment by Pablissimo** [comment]
Give this a bash - will become v0.99 (or v1.0 /o\) and get merged to trunk if it works well enough for you - seems to for my local test projects.

[sonar-typescript-plugin-0.99-SNAPSHOT.zip](https://github.com/Pablissimo/SonarTsPlugin/files/706003/sonar-typescript-plugin-0.99-SNAPSHOT.zip)

New parameters are required:
- sonar.ts.tslintprojectpath - set to probably 'tsconfig.json' or whatever your project file is
- sonar.ts.tslinttypecheck - true/false, defaults to false to send the --type-check parameter too

A note on its behaviour at the minute - if the project fails to type-check you'll not get *any* issues reported just now, because tslint just fails hard. I need to tidy up that handling before things go live for real, I think.

**Comment by nixel2007** [comment]
> sonar.ts.tslintprojectpath

do you set a default value for this parameter? 
Like `./tsconfig.json`?

**Comment by nixel2007** [comment]
And what about to use camelCase for parameters' names? :)

**Comment by Pablissimo** [comment]
Didn't set a default for it, because I can't then tell whether or not to use it if it happens to exist on disk (for example, I've got projects with a tsconfig.json that I'd sooner not use for linting at the mo). Essentially it prevents changing the plugin's behaviour without the user intervening if they upgrade.

Holding off on re-casing the names because I think I'm going to restructure them - they follow the JavaScript plugin naming by and large, which I never really liked. When I do that, I'll probably revisit the above.

**Comment by Pablissimo** [comment]
(The above changes would be probably what tip us into v1.0 territory really - tidy up, obvious version bump to indicate the changed behaviour, refresh all the docs and put some better examples of usage in)

**Comment by Pablissimo** [comment]
Released as v0.99

**Comment by NikitaEgorov** [comment]
@Pablissimo 
Why did you commented this part of code?
```
/*,
    @Property(
        key = TypeScriptPlugin.SETTING_TS_LINT_TYPECHECK,
        defaultValue = "false",
        type = PropertyType.BOOLEAN,
        name = "Forces tslint to run a type-check",
        description = "Equivalent to --type-check tslint argument - requires tslintconfigpath also set",
        project = true,
        global = false
    ),
    @Property(
        key = TypeScriptPlugin.SETTING_TS_LINT_TSCONFIG_PATH,
        defaultValue = "",
        type = PropertyType.STRING,
        name = "Path to tsconfig.json file, if required",
        description = "Required if tslinttypecheck parameter specified, the path to the tsconfig.json file that describes the files to lint and build",
        project = true,
        global = false
    )*/
```

**Comment by Pablissimo** [comment]
Noticed that last night, looks like a local merge gone wrong. Work without it, but you can't set the values in the SonarQube admin panel. Will raise an issue to fix.





-------- Original message --------

**Comment by NikitaEgorov** [comment]
```
2017-01-19T09:07:06.9993123Z ##[error]09:07:06.887 WARN: TsLint reported issues against a file that wasn't sent to it - will be ignored: ****.ts
2017-01-19T09:07:07.0002889Z ##[error]09:07:06.887 WARN: TsLint reported issues against a file that wasn't sent to it - will be ignored: ****.ts
2017-01-19T09:07:07.0002889Z ##[error]09:07:06.887 WARN: TsLint reported issues against a file that wasn't sent to it - will be ignored: ****.ts
```

**Comment by Pablissimo** [comment]
When you pass a project file to tslint it ignores any specific file paths you send it on the command line, so the plug in no longer bothers in that case.

Trick though is that the set of .ts files to be linted as configured by tsconfig.json may not be the same as those under analysis as defined by sonar-project.properties. That warning is just a signal that tslint has reported a lint error against a file that wasn't captured by the sonar runner as part of the analysis set.

That make any sense?



-------- Original message --------

**Comment by NikitaEgorov** [comment]
@Pablissimo 
Now I change ``TsLintSensor.execute``


```
   String pathAdjusted = file.absolutePath().replace('\\', '/').toLowerCase(); //!!!!
            paths.add(pathAdjusted);

...

 for (String filePath : issues.keySet()) {

            List<TsLintIssue> batchIssues = issues.get(filePath);

            if (batchIssues == null || batchIssues.size() == 0) {
                continue;
            }

            String lowerFilePath = filePath.toLowerCase(); //!!!!

            if (!fileMap.containsKey(lowerFilePath)) { //!!!!
                LOG.warn("TsLint reported issues against a file that wasn't sent to it - will be ignored: " + lowerFilePath);
                continue;
            }

            InputFile file = fileMap.get(lowerFilePath); //!!!!
```

Because  
```
 if (!fileMap.containsKey(lowerFilePath)) { //!!!!
                LOG.warn("TsLint reported issues against a file that wasn't sent to it - will be ignored: " + lowerFilePath);
                continue; //!!!!!!!!!!!!!!!!!!
            }
```

**Comment by Pablissimo** [comment]
Yeah that ain't gonna fly! Shall amend, there was some thinking to it but need to see all of it to remember!






-------- Original message --------
