### ISSUE TITLE
Nullpointer when temp file is empty

### ISSUE THREAD

**Issue by t0mmyw** [Pablissimo/SonarTsPlugin#78]
Hi, I am running the plugin and against a long list of ts files. It splits these across 2 commands (not sure if that is relevant). The output file is empty and causes a null pointer when trying to parse it.

tslint version is 3.15.1
node version is 6.9.2
SonarTsPlugin version is 0.96

Stacktrace is 

`15:53:56.420 [INFO] [org.sonarqube.gradle.SonarQubeTask] Sensor Linting sensor for TypeScript files
15:53:56.421 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Found sonar.ts.tslintpath Lint path to be 'D:\codeBase\workingCopy/node_modules/tslint/bin/tslint'
15:53:56.421 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Found sonar.ts.tslintconfigpath Lint path to be 'D:\codeBase\workingCopy/config/tslint/tslint.json'
15:53:56.422 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Path sonar.ts.tslintrulesdir not specified, falling back to null
15:53:56.426 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Using a temporary path for TsLint output: D:\codeBase\workingCopy\build\sonar\.sonartmp\2570028803310674424.tmp
15:53:56.429 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Split 73 files into 2 batches for processing
15:53:56.429 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Executing TsLint with command: node D:\codeBase\workingCopy\node_modules\tslint\bin\tslint --format json --out D:\codeBase\workingCopy\build\sonar\.sonartmp\2570028803310674424.tmp --config D:\codeBase\workingCopy\config\tslint\tslint.json D:/codeBase/workingCopy/... lots of ts files
15:53:59.384 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Executing TsLint with command: node D:\codeBase\workingCopy\node_modules\tslint\bin\tslint --format json --out D:\codeBase\workingCopy\build\sonar\.sonartmp\2570028803310674424.tmp --config D:\codeBase\workingCopy\config\tslint\tslint.json D:/codeBase/workingCopy/... more ts files
15:54:02.905 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':sonarqube'
15:54:02.905 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :sonarqube FAILED
15:54:02.907 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 18: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
15:54:02.917 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :sonarqube (Thread[Daemon worker,5,main]) completed. Took 1 mins 29.217 secs.
15:54:02.917 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 2 mins 48.479 secs, idle: 0.005 secs
15:54:02.918 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 18: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
15:54:02.927 [ERROR] [org.gradle.BuildExceptionReporter] 
15:54:02.928 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:54:02.928 [ERROR] [org.gradle.BuildExceptionReporter] 
15:54:02.928 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:54:02.929 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':sonarqube'.
15:54:02.929 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NullPointerException (no error message)
15:54:02.929 [ERROR] [org.gradle.BuildExceptionReporter] 
15:54:02.929 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:54:02.930 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sonarqube'.
15:54:02.930 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
15:54:02.930 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
15:54:02.930 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
15:54:02.930 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
15:54:02.930 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
15:54:02.931 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:54:02.932 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
15:54:02.933 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:54:02.934 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.935 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.936 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
15:54:02.937 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.lang.Thread.run(Thread.java:745)
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
15:54:02.938 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.pablissimo.sonar.TsLintParserImpl.parse(TsLintParserImpl.java:26)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.pablissimo.sonar.TsLintSensor.execute(TsLintSensor.java:104)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
15:54:02.939 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:240)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
15:54:02.940 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.lang.reflect.Method.invoke(Method.java:498)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.proxy.$Proxy56.execute(Unknown Source)
15:54:02.941 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:93)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at java.lang.reflect.Method.invoke(Method.java:498)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
15:54:02.942 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
15:54:02.943 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
15:54:02.943 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
15:54:02.943 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
15:54:02.943 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:54:02.943 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:54:02.943 [ERROR] [org.gradle.BuildExceptionReporter] 	... 73 more
15:54:02.943 [ERROR] [org.gradle.BuildExceptionReporter] 
15:54:02.943 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:54:02.944 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED`

Thanks

**Comment by t0mmyw** [comment]
I've just noticed this is a duplicate of issue #74 and #72

**Comment by Pablissimo** [comment]
Back from Christmas hols, will fix just now

**Comment by Pablissimo** [comment]
Fixed in [v0.97](https://github.com/Pablissimo/SonarTsPlugin/releases/tag/v0.97), thanks for the report and sorry for the pain!
