### ISSUE TITLE
Add complete example of `sonar-project.properties` file to README

### ISSUE THREAD

**Issue by marklagendijk** [Pablissimo/SonarTsPlugin#81]
For people, like me, who have no prior experience with creating a Sonar project, it would be very helpful to have an full example of a `sonar-project.properties` file. Here is what mine looks like (Angular 2 project):
```
sonar.projectKey=company:my-application
sonar.projectName=My Application
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/app
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts
sonar.ts.tslintconfigpath=tslint.json
sonar.ts.lcov.reportpath=test-results/coverage/coverage.lcov
```

**Comment by Pablissimo** [comment]
Good idea - there've been a couple issues over the past few months with basic setup. Wondering if a blog post might be an idea really, then cross-post it on the wiki I've yet to setup... Can I lift your example when I update the docs next?

**Comment by marklagendijk** [comment]
I created a pull request for this :).

**Comment by nixel2007** [comment]
You can also add this example from my project https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/blob/master/sonar-project.properties
It contains no version, cause I extract it from package.json before sonar-scanner run and pass it through
