### ISSUE TITLE
Tidy up parameter naming

### ISSUE THREAD

**Issue by Pablissimo** [Pablissimo/SonarTsPlugin#85]
Use the SQ parameter name deprecation abilities and restructure parameter names to be more easily readable.

**Comment by Pablissimo** [comment]
First pass at thinking - grouped into:
- General properties (sonar.ts.\*)
- Coverage-related (sonar.ts.coverage.\*) 
- ```tslint```-related (sonar.ts.tslint.\*)

Property names camelCased where needed.

Downside - means that if you have an existing JavaScript project you can't just take your old sonar-project.properties file and replace '.js' with '.ts' and have things like code coverage 'just work', though that's probably atypical.

<table>
<thead><tr><th>Previous</th><th>New</th></tr></thead>
<tbody>
<tr><td>sonar.ts.excludetypedefinitionfiles</td><td>sonar.ts.excludeTypeDefinitionFiles</td></tr>
<tr><td>sonar.ts.forceZeroCoverage</td><td>sonar.ts.coverage.forceZero</td></tr>
<tr><td>sonar.ts.ignoreNotFound</td><td>sonar.ts.coverage.ignoreNotFound</td></tr>
<tr><td>sonar.ts.lcov.reportpath</td><td>sonar.ts.coverage.lcovReportPath</td></tr>
<tr><td>sonar.ts.tslintenabled</td><td>sonar.ts.tslint.enabled</td></tr>
<tr><td>sonar.ts.tslintpath</td><td>sonar.ts.tslint.path</td></tr>
<tr><td>sonar.ts.tslintconfigpath</td><td>sonar.ts.tslint.configPath</td></tr>
<tr><td>sonar.ts.tslinttimeout</td><td>sonar.ts.tslint.timeout</td></tr>
<tr><td>sonar.ts.tslintrulesdir</td><td>sonar.ts.tslint.rulesDir</td></tr>
<tr><td>sonar.ts.ruleconfigs</td><td>sonar.ts.tslint.ruleConfigs</td></tr>
<tr><td>sonar.ts.tslinttypecheck</td><td>sonar.ts.tslint.typeCheck</td></tr>
<tr><td>sonar.ts.tslintprojectpath</td><td>sonar.ts.tslint.projectPath</td></tr>
</tbody>
</table>

Still want to rethink the coverage LCOV report path property naming, since there's the outstanding 'split into UT and IT values' issue #56, and maybe rename 'ruleConfigs' to something less vague.

**Comment by nixel2007** [comment]
> split into UT and IT values

SQ 6.2 drop the difference between UT and IT. Now it is just Coverage

**Comment by Pablissimo** [comment]
Takes care of that issue then!




-------- Original message --------

**Comment by Pablissimo** [comment]
Only change made to the above is ```sonar.ts.coverage.forceZero``` becomes ```sonar.ts.coverage.forceZeroIfUnspecified``` to make it actually make any sense.
