### ISSUE TITLE
Code Smells Always 0 ?

### ISSUE THREAD

**Issue by kgiroux** [Pablissimo/SonarTsPlugin#90]
Hi,

I dont understand why the code Smell is always 0. 

when i check the installation guide, i visit the following link, but still have 0.

It is a bug or a misconfiguration ? 

https://sonar.pablissimo.com/overview?id=20352
https://sonar.pablissimo.com/overview?id=18822

Sincerely,

**Comment by Pablissimo** [comment]
On the demo site it's just because those code bases happen to be clean relative to their rules files (they used to be dirtier, sadly they aren't very good as a demo case any more)

So are you having issues with your own installation? Would start by running the scanner with -X -e options to see what is happening, and post or email the log.




-------- Original message --------

**Comment by kgiroux** [comment]
Just email the stack on hello@pablissimo.com

**Comment by Pablissimo** [comment]
So to me everything in the log looks good. Next step - find the command line in the log you sent and try to run it in a shell - you can omit the --out parameter. See if you get any issues reported.

If you don't, congrats! Your code is clean. If you do, check:
- whatever user is running the scanner has write access to the temp path descrobed by the --out parameter
- that on SQ the rules profile actually has rules enabled, and that they've not all defaulted to Off

I need to add better logging of the tslint output to aid this sort of thing, but let me know how you get on. At a conference this week but have little bits of downtime...

**Comment by Pablissimo** [comment]
Also: what version of ```tslint``` are you using?

**Comment by kgiroux** [comment]
tslint version : tslint@4.3.1 
If you don't, congrats! Your code is clean. If you do, check.  ===> it seems difficult to believe because, i try the following command  with the tslint in my project and i have a big file of error.
"lint": "tslint -t checkstyle --force -o target/checkstyle-result.xml \"src/**/*.ts\"",

**Comment by Pablissimo** [comment]
But did you run it with the specific command line the plug in was sending? Entirely possible there is a bug, just want to make sure we're not missing something

**Comment by kgiroux** [comment]
Without changing anything, it is working.

Thank for your help
