### ISSUE TITLE
Add option to specify tslint output as a file

### ISSUE THREAD

**Issue by sevaru** [Pablissimo/SonarTsPlugin#91]
It's more like a question then a bug.

**TL,TR**
* Add option to set file with tslint results.

In our project "myproject" (sonar project, one git repo) we have a problem.
It consist of several web project (framework, sample-app, tests, etc).
All of them compiled independently (each has it's package.json, tsconfig.json, etc).
But we need to collect all the quality data in one place ("myproject").

**Failed solution**
My first attempt is to create single tslint.json and tsconfig.json for tslint but 
"--type-check" option requires this project to be compilable.
So, we have duplicate dependencies (e.g. framework has it's own d.ts files for kendo in node_modules and sample-app has it's own dependency on framework and kendo as well and has d.ts files of kendo in node_modules too).
This is not only for kendo but for other libs too.

**Current solution**
So my current suggestion is to run tslint by ourselves for each project separately and concat tslint output to one file and then give it to tslint-sonar plugin.

**Comment by Pablissimo** [comment]
On board with that, as an idea - plenty of projects have a tslint run as part of their build process so this would save them having to rerun. Shall investigate (or feel free to create a PR)



-------- Original message --------

**Comment by NikitaEgorov** [comment]
I try to implement changes
https://github.com/NikitaEgorov/SonarTsPlugin/commit/4926c32d147a7ace1b1729cffb3f106783b2e921

**Comment by Pablissimo** [comment]
Changes you made looked good, I've made minor tweaks but it's now merged into master and will form part of the 1.0 release which is my next thing to do!
