### ISSUE TITLE
Unit test coverage plugin

### ISSUE THREAD

**Issue by parky128** [Pablissimo/SonarTsPlugin#97]
Hi,

In the readme  it says the plugin is unfinished due to - 'Incomplete unit test coverage of the plugin'

What exactly is not complete? Should the plugin work fine reading lcov files already?

Thanks

**Comment by Pablissimo** [comment]
It refers to testing of the plugin itself, which used to be more sparse than at present. That line can probably be removed and the whole readme likely updated when I get a chance to roll a 1.0 release.



-------- Original message --------

**Comment by parky128** [comment]
Ok great thanks :+1:

**Comment by Pablissimo** [comment]
Removed confusing comment from the readme.
